import type { Question } from "../../types.js";

/** [moduleId, text, options, correctIndex, explanation] */
export const questions: Question[] = [

// d1
["d1","A node stops replying. What can you conclude from the silence alone?",["It has crashed","It is overloaded","Nothing: a crash, a slow process and a broken link are indistinguishable","The network is partitioned"],2,"Silence is the same evidence in all three cases, which is why a timeout is a decision rather than a measurement. Picking crash, overload or partition all commit to one explanation that the evidence does not support — and an algorithm that acts on the wrong one is unsafe."],
["d1","Which failure model subsumes all the others?",["Crash-stop","Crash-recovery","Omission","Byzantine"],3,"The models nest: crash-stop ⊂ crash-recovery ⊂ omission ⊂ Byzantine. A Byzantine process may do anything, including behaving exactly like a crashed or omitting one, so tolerating it covers the rest. Crash-stop is the narrowest, not the widest; crash-recovery and omission each sit inside Byzantine."],
["d1","Why is crash-recovery harder to reason about than crash-stop?",["Recovery takes longer than a restart","A recovered process may have forgotten what it promised and contradict its own past","Recovered processes run more slowly","It requires more nodes"],1,"A crash-stop process is silent forever, so it can never contradict itself. A recovered one can acknowledge a write, lose it, and come back denying it — which is why these algorithms specify what must reach stable storage before a message is sent. Recovery duration and speed are performance concerns, not correctness ones, and node count is a quorum question, not a failure-model one."],
["d1","What does the partially synchronous model actually assume?",["Message delays are bounded and the bound is known","Bounds exist but are unknown, or hold only after an unknown stabilisation time","Half the messages arrive on time","Clocks are synchronised to within a known skew"],1,"That is the definition: you get eventual good behaviour without ever being told when it started. A known bound is the synchronous model, which no shared network provides. It says nothing about a fraction of messages, and nothing about clocks — clock synchronisation is a separate axis entirely."],
["d1","A client retries a request after a timeout. What has it just guaranteed?",["The operation runs exactly once","The operation may now run twice","The first request was definitely lost","The server will deduplicate it"],1,"The timeout does not prove the first request was lost — it may have been executed with only the reply lost, so the retry can produce a second execution. Exactly-once is not a delivery guarantee but an end-to-end property, and deduplication only happens if someone built it, keyed on a client-generated request id."],
["d1","Which of these is a receive-omission failure's defining hazard?",["The process crashes without warning","The process reports itself healthy while silently missing traffic","The process sends corrupted data","The process runs out of disk"],1,"A receive-omission fault is invisible to the faulty process: logs are clean, metrics are green, and it is missing half the cluster's messages. Self-reported health checks cannot detect it. A crash is a different model, corrupted data is Byzantine behaviour, and a full disk is a local resource failure that the process can see."]

];
