import type { Question } from "../../types.js";

/** [moduleId, text, options, correctIndex, explanation] */
export const questions: Question[] = [

// d1
["d1","A node stops replying. What can you conclude from the silence alone?",["It has crashed","It is overloaded","Nothing: a crash, a slow process and a broken link are indistinguishable","The network is partitioned"],2,"Silence is the same evidence in all three cases, which is why a timeout is a decision rather than a measurement. Picking crash, overload or partition all commit to one explanation that the evidence does not support — and an algorithm that acts on the wrong one is unsafe."],
["d1","Which failure model subsumes all the others?",["Crash-stop","Crash-recovery","Omission","Byzantine"],3,"The models nest: crash-stop ⊂ crash-recovery ⊂ omission ⊂ Byzantine. A Byzantine process may do anything, including behaving exactly like a crashed or omitting one, so tolerating it covers the rest. Crash-stop is the narrowest, not the widest; crash-recovery and omission each sit inside Byzantine."],
["d1","Why is crash-recovery harder to reason about than crash-stop?",["Recovery takes longer than a restart","A recovered process may have forgotten what it promised and contradict its own past","Recovered processes run more slowly","It requires more nodes"],1,"A crash-stop process is silent forever, so it can never contradict itself. A recovered one can acknowledge a write, lose it, and come back denying it — which is why these algorithms specify what must reach stable storage before a message is sent. Recovery duration and speed are performance concerns, not correctness ones, and node count is a quorum question, not a failure-model one."],
["d1","What does the partially synchronous model actually assume?",["Message delays are bounded and the bound is known","Bounds exist but are unknown, or hold only after an unknown stabilisation time","Half the messages arrive on time","Clocks are synchronised to within a known skew"],1,"That is the definition: you get eventual good behaviour without ever being told when it started. A known bound is the synchronous model, which no shared network provides. It says nothing about a fraction of messages, and nothing about clocks — clock synchronisation is a separate axis entirely."],
["d1","A client retries a request after a timeout. What has it just guaranteed?",["The operation runs exactly once","The operation may now run twice","The first request was definitely lost","The server will deduplicate it"],1,"The timeout does not prove the first request was lost — it may have been executed with only the reply lost, so the retry can produce a second execution. Exactly-once is not a delivery guarantee but an end-to-end property, and deduplication only happens if someone built it, keyed on a client-generated request id."],
["d1","Which of these is a receive-omission failure's defining hazard?",["The process crashes without warning","The process reports itself healthy while silently missing traffic","The process sends corrupted data","The process runs out of disk"],1,"A receive-omission fault is invisible to the faulty process: logs are clean, metrics are green, and it is missing half the cluster's messages. Self-reported health checks cannot detect it. A crash is a different model, corrupted data is Byzantine behaviour, and a full disk is a local resource failure that the process can see."]
,

// d2
["d2","Two events on different processes have Lamport timestamps L(a) = 7 and L(b) = 9. What follows?",["a happened before b","b happened before a","Nothing about causality — the implication only runs the other way","a and b are concurrent"],2,"a → b implies L(a) < L(b), but not the converse: two concurrent events get whatever values their own histories produced, and one is necessarily smaller. b cannot have happened before a (that would need L(b) < L(a)), but concurrency is not proven either — Lamport values alone cannot distinguish the two cases, which is what vector clocks are for."],
["d2","Which part of the Lamport algorithm is what actually enforces causality across a message?",["Incrementing the counter on every local event","Taking max(L, m.L) + 1 on receive","Attaching the counter to the outgoing message","Breaking ties on process id"],1,"The max drags the receiver's counter past everything the sender knew, so a receive can never be stamped below its send. Local increments only order events within one process; attaching the value is the transport that makes the max possible but does not itself order anything; the tiebreak merely turns the partial order into an arbitrary total one."],
["d2","Two versions of a value carry vector clocks [2,1,0] and [1,2,0]. What is their relationship?",["The first supersedes the second","The second supersedes the first","They are concurrent and the conflict must be resolved","They are identical"],2,"Neither vector is ≤ the other elementwise: 2 > 1 in the first position and 1 < 2 in the second. Supersession would require every entry of one to be ≤ the corresponding entry of the other, and identity would require all entries equal. This is exactly the case a store must not silently collapse."],
["d2","A client reads x = 1 from a node whose clock runs ahead, and because of what it read writes x = 2 on a node whose clock runs behind. What does last-write-wins on wall-clock timestamps do?",["Keeps x = 2, since it was written later","Discards x = 2, although it causally depends on x = 1","Rejects the second write with a conflict error","Keeps both versions as siblings"],1,"The second write carries the smaller timestamp, so the comparison keeps the first and drops the second — an effect ordered before its cause, with success already returned to the client. No error is raised, which is what makes it dangerous; siblings are what a vector-clock store would produce instead, and this one never detects the conflict at all."],
["d2","Which clock should measure how long a local operation took?",["The wall clock, because NTP keeps it accurate","The monotonic clock, which never steps backwards","Either — they differ only in resolution","A Lamport clock"],1,"A wall clock can be stepped backwards by a correction, so subtracting two readings can yield a negative duration. The monotonic clock cannot be compared across machines, but a local duration does not need that. A Lamport clock counts events, not seconds, and cannot express a duration at all."],
["d2","Under happens-before, when are two events concurrent?",["When their timestamps are equal","When neither is reachable from the other by the three rules","Whenever they occur on different processes","When they fall within the clock skew window"],1,"Concurrency is defined as the absence of the relation in both directions — no local ordering, no message path, no chain of the two. Events on different processes are frequently ordered, by messages. And the definition mentions no clock at all, so no skew window enters into it."]

];
