import type { Question } from "../../types.js";

/** [moduleId, text, options, correctIndex, explanation] */
export const questions: Question[] = [

// a1
["a1","What does an instruction set architecture specify?",["How many cycles each instruction takes","The visible results — registers, instruction effects, memory ordering, exceptions — and nothing about how they are achieved","The cache hierarchy","The pipeline depth"],1,"That separation is what lets code compiled decades ago run on a processor whose internal organisation shares nothing with the original. Timing, caches and pipeline structure are all implementation choices the contract deliberately leaves open."],
["a1","How did the RISC versus CISC argument resolve?",["RISC won and x86 was abandoned","x86 decodes its variable-length instructions into fixed-length micro-operations and runs a RISC-style out-of-order core behind them","CISC won because compilers improved","They remain fundamentally incompatible approaches"],1,"Both happened: RISC won the technical argument about how to build an execution engine, and x86 won the market by keeping its encoding as a front end. What survives of the distinction is decode cost, not philosophy."],
["a1","Why does x86 keep a µop cache?",["To store frequently used data","To skip the expensive variable-length decoder on hot loops","To hold predicted branch targets","To reduce memory bandwidth"],1,"Variable-length decode is genuinely harder and hungrier than fixed-length, so caching the already-decoded operations removes that cost where it matters most. It caches operations, not data or targets."],
["a1","Why does a processor have hundreds of physical registers when the ISA names sixteen?",["To support multiple threads","Register renaming maps each architectural write onto a fresh physical register, removing false dependencies","To cache memory operands","For compatibility with older architectures"],1,"Without renaming, a large out-of-order window would fill with WAR and WAW conflicts that are name collisions rather than real dependencies. Thread state is a separate mechanism."],
["a1","What is the consequence of having only sixteen architectural registers?",["Programs are limited in size","A compiler that runs out must spill to the stack, consuming issue slots and lengthening dependency chains","Instructions must be longer","Recursion is limited"],1,"Spills usually hit L1 so they are not catastrophic, but they are not free either — which is one reason the same code often needs fewer instructions on AArch64 with its 31 names."],
["a1","What does fixed-length instruction encoding buy?",["Denser code","Trivially parallel decode, because instruction boundaries are known before decoding","Faster execution","More addressing modes"],1,"Variable-length encoding gives the denser code and therefore fewer instruction-cache misses; fixed length gives the easy decode. Both are real, which is why RISC-V added a compressed extension."],
["a1","Why is instruction count a poor predictor of execution time?",["Compilers optimise it away","Time depends on dependencies, branches and memory access patterns, which two sequences with equal instruction counts can differ in enormously","Instructions have variable lengths","Modern CPUs execute instructions in parallel by definition"],1,"The relevant unit is the cycle and the relevant ratio is IPC, which can vary by an order of magnitude for identical instruction counts. \"Fewer instructions\" is not an optimisation argument on its own."],
["a1","In what sense does the processor not execute your program?",["It executes a different program entirely","It fetches ahead, predicts, reorders, and discards work — and is only required to produce the results the sequential model specifies","It executes it in a virtual machine","It skips instructions it decides are unnecessary"],1,"The results are guaranteed and the timing and side effects are not, which is exactly the gap module a13 exploits. Nothing is skipped and nothing is virtualised."],

// a2
["a2","Why does negating INT_MIN overflow?",["Integers cannot be negative","Two's complement is asymmetric by one, so the most negative value has no positive counterpart","The sign bit cannot be cleared","It is a compiler limitation"],1,"There are as many negatives as positives plus zero. The same asymmetry makes abs(INT_MIN) overflow and INT_MIN / −1 raise a hardware exception on x86 — a division that traps with no zero divisor in sight."],
["a2","What is the difference between unsigned and signed integer overflow in C?",["None, both wrap","Unsigned wraps and is defined; signed is undefined behaviour, which the compiler may assume cannot happen","Signed wraps and unsigned traps","Both are undefined"],1,"The distinction has teeth: given if (x + 1 < x) with signed x, the compiler may reason that the condition is always false and delete the check — removing an overflow check precisely because it checks for overflow."],
["a2","Why is -1 < 1u false in C?",["Operator precedence","The signed operand is converted to unsigned, so −1 becomes a very large value","Comparison with literals is undefined","The compiler optimises it away"],1,"Implicit conversion in mixed signed/unsigned comparison is why comparing a signed loop counter against an unsigned size() is such a persistent bug source."],
["a2","How many bits does binary64 give the exponent and fraction?",["8 and 23","11 and 52","12 and 51","16 and 47"],1,"One sign, eleven exponent with bias 1023, and fifty-two fraction bits with an implicit leading 1 — about 15 to 17 decimal digits. The first option is binary32."],
["a2","Why is 0.1 + 0.2 not exactly 0.3?",["Rounding errors accumulate in the adder","One tenth has no exact binary representation, so both operands are already approximations","The processor uses extended precision internally","IEEE 754 is imprecise by design"],1,"Binary fractions represent exactly those values whose denominator is a power of two, and a tenth is not one. It is a base conversion issue present before any arithmetic happens."],
["a2","What does the non-associativity of floating-point addition prevent?",["Using floats in loops","A compiler from auto-vectorising a reduction, because vector accumulators sum in a different order","Comparing floats for equality","Using floats for money"],1,"Reassociation changes the computed result, so the compiler may not do it silently — which is the most common reason an obviously vectorisable sum is not vectorised. -ffast-math grants permission and is a correctness change."],
["a2","What is catastrophic cancellation?",["Overflow to infinity","Subtracting nearly equal values, which annihilates the leading digits and promotes rounding error into the significant ones","Underflow to zero","A NaN propagating through a computation"],1,"The magnitude of the result is small while its relative error is large, which is why numerically stable formulations avoid the subtraction rather than trying to be more careful about it."],
["a2","Why does NaN break a sort comparator?",["It sorts to the end","It is unordered with respect to everything including itself, so the comparator violates the strict weak ordering the sort requires","It compares equal to every value","Sorting algorithms cannot handle it"],1,"NaN == NaN is false and so are <, > and ==, which can drive a sort implementation out of bounds. The same property breaks min/max reductions and hash lookups."],
["a2","Why should money never be held in binary floating point?",["Floats are too slow","Most exact decimal amounts have no exact binary representation, and a currency amount is exact by definition","Floats have insufficient range","Rounding modes are not standardised"],1,"Use integer minor units or a decimal type. Range and speed are not the problem — representability is."],

// a3
["a3","What does pipelining improve?",["The latency of each instruction","Throughput — one instruction completes per cycle, though each still takes all its stages","Both equally","Cache hit rate"],1,"It slightly worsens latency, because the pipeline registers between stages add real delay. The laundry analogy holds: one load still takes wash-dry-fold."],
["a3","Which of the three hazard types is a true dependency?",["Structural","RAW — read after write","WAR — write after read","WAW — write after write"],1,"Only RAW means information genuinely has to flow. WAR and WAW are name collisions caused by an ISA with few register names, and renaming removes them entirely."],
["a3","What does forwarding do?",["Predicts the next instruction","Routes a result from where it is produced directly to where it is needed, instead of waiting for write-back","Reorders instructions","Fetches ahead of the branch"],1,"It eliminates almost every arithmetic RAW stall by noticing the result exists in the EX output long before it reaches the register file."],
["a3","Which stall survives forwarding, and why?",["The structural hazard, because hardware cannot be duplicated","The load-use hazard, because a load produces its value in MEM rather than in EX","The control hazard, because branches cannot be forwarded","The WAW hazard, because two writes conflict"],1,"An instruction consuming a loaded value is one cycle too early no matter how the wires are arranged. Classically the compiler fills that slot; an out-of-order machine does it dynamically."],
["a3","Roughly what does a mispredicted branch cost on a modern deep pipeline?",["3 cycles","15–20 cycles","50–100 cycles","200 cycles"],1,"Roughly the pipeline depth, which on a wide core is dozens of instructions' worth of discarded work — and is why prediction accuracy above 99% is a requirement rather than a luxury. The last figure is a DRAM access."],
["a3","What was the lesson of the Pentium 4's NetBurst architecture?",["Deeper pipelines are always better","Depth allows a higher clock and raises the misprediction penalty, and past a point the second effect wins","Clock speed does not matter","CISC cannot be pipelined"],1,"It reached about thirty stages chasing frequency and was beaten in real work by shorter-pipeline designs at lower clocks — one of the clearest cases of a single metric optimised past the point where it predicts performance."],
["a3","In time = instructions × CPI × cycle time, why is optimising one term alone misleading?",["The formula is only an approximation","The three interact — reducing instruction count can raise CPI, and reducing cycle time by adding depth raises it too","CPI cannot be measured","Cycle time is fixed by the hardware"],1,"A compiler that emits fewer but harder-to-predict instructions can lose overall, which is exactly why the terms have to be considered together."],
["a3","What does an ideal CPI below 1 require?",["A deeper pipeline","Superscalar issue — more than one instruction started per cycle","Perfect branch prediction","A larger cache"],1,"Pipelining alone tops out at one per cycle; going below requires multiple execution units and a front end wide enough to feed them."],

// a4
["a4","Why must a processor predict branches rather than wait?",["Waiting is more accurate","The fetch stage needs the next address a dozen cycles before the branch resolves, so waiting means a bubble on every branch","Branches are rare","Prediction saves power"],1,"With a branch roughly every five instructions, waiting would leave the machine empty most of the time. Prediction is compulsory rather than an optimisation."],
["a4","Why are bimodal predictors two bits rather than one?",["To predict the target as well as the direction","So a single anomalous outcome does not flip the prediction — a loop's final exit does not mispredict the next entry","To track two branches per entry","To store the branch address"],1,"A one-bit predictor on a loop misses twice per exit, on the way out and on the way back in; two bits absorb the exit and miss once. The target is a separate structure."],
["a4","What is the key insight behind two-level and gshare predictors?",["Branches are usually taken","Branches correlate, so the table is indexed by the branch address combined with a history of recent outcomes","Loops dominate branch behaviour","Backward branches behave differently from forward ones"],1,"if (x > 0) followed by if (x > 10) are not independent, and history captures that relationship. The last option is the static heuristic that preceded all of this."],
["a4","Why do polymorphic call sites and bytecode interpreters mispredict heavily?",["They execute more instructions","They are indirect branches, which need a predicted target rather than just a direction","They defeat the return address stack","They are always taken"],1,"A computed target with many possible values is far harder than a binary direction, which is why devirtualisation and per-opcode dispatch sites produce large speedups unrelated to instruction count."],
["a4","Why can sorting an array make a subsequent filtering loop several times faster?",["Sorted data is more cache friendly","The branch becomes predictable — long runs of taken then not-taken — so the mispredictions disappear","The compiler vectorises sorted data","Fewer elements pass the filter"],1,"The instruction count and the memory traffic are unchanged. Only the predictability of the data-dependent branch changed, which is the whole effect."],
["a4","Why do microbenchmarks with fixed inputs mislead about branch cost?",["They run too few iterations","They train the predictor perfectly, reporting a number the same code will not achieve on varied production data","They are compiled differently","They keep the data in cache"],1,"Cache effects are a separate distortion; this one is specifically about the predictor learning a pattern that production input does not have. If the branch depends on input, the benchmark must vary it the way production does."],
["a4","When is branchless code the right choice?",["Always — branches are expensive","When the branch is genuinely unpredictable, since branchless has a fixed cost and always computes both sides","When the branch is highly predictable","Only in cryptographic code"],1,"A branch predicted at 99% should stay a branch; one at 50% should not. In cryptography branchless is a correctness requirement rather than an optimisation, because a branch on secret data leaks it through timing."],
["a4","What trace does discarded speculative work leave?",["None at all","No architectural trace, but microarchitectural state such as a cache line pulled in by a squashed load","A recorded exception","An entry in the branch history"],1,"Registers and memory are restored, which is why speculation is safe under the ISA contract — and the surviving cache state is exactly what module a13 turns into a channel."],

// a5
["a5","What is the difference between superscalar and out-of-order execution?",["They are the same thing","Superscalar issues several instructions per cycle; out-of-order executes them as their operands become ready regardless of program order","Superscalar is for integers, out-of-order for floating point","Out-of-order requires superscalar"],1,"They are separable, and each is limited alone: a wide in-order machine stalls entirely on its oldest instruction, and a one-wide out-of-order machine can reorder but not overlap."],
["a5","What does register renaming eliminate?",["RAW dependencies","WAR and WAW hazards, which are name collisions rather than real dependencies","Cache misses","Branch mispredictions"],1,"RAW is a true dependency and cannot be removed by renaming — information genuinely has to flow. Renaming maps each architectural write to a fresh physical register."],
["a5","What does in-order retirement from the reorder buffer provide?",["Higher throughput","Precise exceptions, speculation recovery and the sequential contract — all from one rule","Lower latency","Better cache behaviour"],1,"Results become architecturally visible only at retirement, so a fault can be raised with the state exactly as if execution had stopped there, and wrong-path instructions never retire."],
["a5","Why can one cache miss stall a core that has plenty of independent work?",["The independent work also misses","The missing instruction blocks the head of the reorder buffer, so nothing younger can retire and the buffer fills","The scheduler deprioritises it","Memory access is serialised"],1,"The independent work executes fine — it just cannot retire, and once the ROB is full the front end stalls entirely. It is a retirement constraint, not an execution one."],
["a5","An instruction has latency 4 and throughput 2 per cycle. When does the latency matter?",["Always","Only when the next operation needs this result","Only in loops","Only when the units are busy"],1,"The same instruction costs four cycles or half of one depending entirely on the surrounding code, which is why confusing the two numbers is the most common error in reading an instruction table."],
["a5","Why does splitting a reduction into four accumulators speed it up?",["It uses fewer instructions","It breaks the dependency chain, so the four partial sums proceed in parallel instead of each waiting for the last","It improves cache locality","It enables branch prediction"],1,"It does slightly more work and is nearly four times faster, because the limit was the chain rather than the instruction count. For floating point it also changes the answer, which is why the compiler will not do it unaided."],
["a5","What are the four categories of top-down analysis?",["L1, L2, L3 and DRAM misses","Retiring, bad speculation, front-end bound and back-end bound","Integer, floating point, memory and branch","User, system, idle and wait"],1,"They partition every issue slot and have non-overlapping remedies, which is the point — attacking a memory-bound loop with wider vectors is the standard wasted afternoon."],
["a5","A loop is memory bound. What will wider vectors buy?",["Roughly the vector width in speedup","Nothing — the bottleneck was never the arithmetic","Half the vector width","It depends on the instruction mix"],1,"This is the single most common misdirected optimisation, and the top-down breakdown identifies it before any code is written."],

// a6
["a6","What two properties make caching work at all?",["Speed and capacity","Temporal and spatial locality","Associativity and replacement policy","Prefetching and write-back"],1,"Temporal locality justifies keeping recent data; spatial locality justifies fetching in 64-byte lines rather than words. Without both, a cache would be useless."],
["a6","What does the 64-byte line granularity imply?",["Data must be 64-byte aligned","Touching one byte costs the same as touching all sixty-four","Caches can only hold 64-byte objects","Writes must cover a whole line"],1,"That is why array-of-structs and struct-of-arrays can differ by a factor of ten on the same algorithm — the unused fields still occupy the lines you fetched."],
["a6","In a set-associative cache, what does the index field select?",["Which way within a set","Which set the line may occupy","The byte within the line","The tag to compare against"],1,"The address splits into tag, index and offset; the index chooses the set, the line may go in any way within it, and the offset selects the byte. The index bits are not stored, because they are implied by which set holds the line."],
["a6","Which of the three Cs is fixed by increasing associativity?",["Compulsory","Capacity","Conflict","All three"],1,"Conflict misses happen when a line is evicted by another mapping to the same set while other sets sit idle. Compulsory misses need prefetching or less data; capacity misses need a smaller working set."],
["a6","Why does walking an array with a large power-of-two stride perform so badly?",["The prefetcher cannot detect it","Every access lands in the same few sets, so a large cache behaves like a tiny one","The addresses are misaligned","It causes TLB misses"],1,"The index bits are identical for all those addresses, so they compete for one set's ways. Padding a matrix dimension by one element breaks the alignment and usually removes it entirely."],
["a6","What does write-allocate mean in practice?",["Writes go directly to memory","Writing memory you never read still reads it, because a write miss fetches the line first","Writes are buffered until eviction","Writes allocate new cache lines only when space is free"],1,"Filling a large buffer therefore pulls every line in from DRAM only to overwrite it, doubling the traffic — which is what non-temporal stores exist to avoid."],
["a6","Why is L1 so small?",["Transistors are expensive","Its latency is on the critical path of every load, and a bigger cache is a slower one","Larger caches have worse hit rates","It must fit on the same die as the core"],1,"The whole hierarchy exists because no single memory can be both large and fast, and each level is a different point on that trade."],
["a6","Where do cores interfere with each other in the cache hierarchy?",["L1, which is shared between hyperthreads only","The shared L3, where one core's streaming evicts another's working set","The store buffer","The TLB"],1,"That is the mechanism behind the noisy-neighbour effect. L1 and L2 are private per core, so contention appears at the shared level."],

// a7
["a7","Why is pointer chasing so much slower than array traversal?",["Pointers are larger than indices","The next address is unknown until the current load returns, so only one miss can be outstanding and the latencies serialise","Allocators scatter nodes randomly","It defeats the branch predictor"],1,"Allocation locality contributes, but the principal cause is the dependency: an array issues all its misses at once and a chain issues them one at a time. A hundred nodes cost a hundred full round trips."],
["a7","What caps a single thread's achievable memory bandwidth?",["DRAM speed","The number of outstanding-miss buffers, typically ten to sixteen","The cache line size","The memory controller"],1,"With many misses in flight their latencies overlap, so effective cost per miss is DRAM latency divided by the number outstanding. That is Little's Law applied to memory."],
["a7","Which pattern can a hardware prefetcher NOT handle?",["Sequential access","A constant negative stride","An indirect index such as A[B[i]]","A multi-line stride"],2,"Prefetchers recognise next-line and constant strides in either direction. They cannot follow a pointer, predict an indirect index, or cross a page boundary."],
["a7","Why does a sequential scan take a fresh compulsory miss at every page boundary?",["The TLB must be reloaded","The prefetcher stops at 4 KiB rather than risk a translation it has no reason to believe in","Pages are not contiguous in physical memory","The page cache is per-page"],1,"That limit is one reason huge pages help streaming workloads. The TLB reload is a separate and additional cost."],
["a7","When is a software prefetch instruction worth using?",["Whenever a loop misses","For indirect or pointer-based traversals whose future addresses are computable ahead of time","In every hot loop","Never"],1,"Hardware is generally better informed for regular patterns, and software prefetch consumes issue slots and buffers. The exception is exactly what hardware cannot see — prefetching A[B[i+16]] while processing A[B[i]]."],
["a7","When is struct-of-arrays the wrong choice?",["When the data is small","When a pass touches every field of each object","When there are many objects","When the fields have different types"],1,"SoA wins when a pass reads one field of many objects, because AoS wastes most of each fetched line. If every field is used, the line was fully used already and SoA adds indirection for nothing."],
["a7","Why does interleaving several independent lookups speed up a hash table?",["It improves branch prediction","It gives the machine several concurrent misses where a simple loop gives one at a time","It reduces the number of hashes computed","It improves cache line utilisation"],1,"This is the direct application of memory-level parallelism: the buffers exist, and a serial loop simply does not use them."],
["a7","Why do B-trees beat binary trees in memory, not just on disk?",["They use less memory","Cache-line-sized nodes mean fewer dependent loads for the same element count","They are easier to balance","They avoid pointer chasing entirely"],1,"Each dependent load costs a full latency that cannot be overlapped, so reducing their count matters more than reducing comparisons. They still chase pointers — just far fewer times."],

// a8
["a8","What is the difference between coherence and consistency?",["They are synonyms","Coherence is about agreement on one location and is solved in hardware; consistency is about the order of operations on different locations and is architecturally visible","Coherence applies to caches, consistency to memory","Consistency is a subset of coherence"],1,"Coherence is not optional and cannot be turned off. Consistency differs between architectures and is what fences and atomics exist to control."],
["a8","In MESI, what must happen before a core can write a line?",["Nothing — writes are always permitted locally","It must hold the line Modified or Exclusive, which means invalidating every other copy","The line must be written to memory first","All other cores must be stalled"],1,"Reading is shareable and cheap; writing is exclusive and requires a conversation. That asymmetry produces every performance consequence in the module."],
["a8","How expensive is read-only sharing of a cache line between many cores?",["It scales badly with core count","It is free — any number of cores may hold the line in Shared and read at full speed","It costs one invalidation per reader","It requires the line to be Modified"],1,"A shared immutable lookup table costs nothing. It is written lines that ping-pong between cores at tens to hundreds of cycles per transfer."],
["a8","What is the mechanical cause of false sharing?",["Two threads using the same variable","The cache line, not the variable, is the unit of coherence — so two variables in one line ping-pong as if shared","Compiler reordering","Insufficient associativity"],1,"Padding to 64 bytes separates them. Nothing in the source looks wrong, which is what makes it so hard to spot."],
["a8","Why does a shared atomic counter scale so badly?",["Atomics are implemented in software","Each operation needs the line exclusively, so invalidation traffic grows with the number of participants","Atomics disable interrupts","The counter overflows"],1,"An uncontended atomic increment is tens of cycles; a contended one pays the invalidation round trip every time. The standard fix is a per-core counter summed on read."],
["a8","What reordering does x86's TSO model permit?",["None","StoreLoad only — a later load can complete before an earlier store leaves the store buffer","StoreStore only","All reorderings"],1,"That single permitted reordering is what makes both threads miss each other's write in the classic two-thread example, which no interleaving allows."],
["a8","Why is x86's relatively strong memory model a trap?",["It is slower than weaker models","Code with missing barriers often works on x86 by accident and fails on ARM, where the same omission is exposed","It prevents optimisation","It requires more fences"],1,"Which is why portable reasoning has to happen at the language memory model — write to the C++, Java or Go model and the compiler emits the right barriers per target."],
["a8","Why are acquire and release cheaper than sequential consistency?",["They are implemented in hardware","They constrain less, so fewer barriers are emitted","They apply only to reads","They skip the coherence protocol"],1,"Sequential consistency requires a total order over all such operations, which on x86 means a store plus a fence. Acquire-release constrains only the necessary direction."],

// a9
["a9","Where does SIMD's speedup actually come from?",["Faster arithmetic units","One decode slot, one issue slot and one dependency edge covering many elements","Wider memory buses","Reduced branch count"],1,"The arithmetic per element is not faster; the per-instruction overhead is amortised across the lanes. Which is also why a memory-bound loop gains nothing from wider vectors."],
["a9","What makes ARM's SVE architecturally interesting?",["It supports more data types","The vector width is not in the instruction encoding, so one binary runs at any implementation width","It has more registers","It is faster than AVX-512"],1,"That is the ISA principle applied to vectors — state what happens, not how wide the hardware is — and it avoids the recompile-per-width treadmill that successive x86 extensions created."],
["a9","Two pointers are passed to a loop and it does not vectorise. What is the likely reason?",["The loop is too short","The compiler must assume the pointers may alias, so the vector form would not be equivalent","Floating point is involved","The trip count is unknown"],1,"restrict, __restrict__ or an independence pragma tells the compiler otherwise. All four options can block vectorisation, but aliasing is the one that two raw pointers specifically trigger."],
["a9","Why is a floating-point sum reduction often not auto-vectorised?",["Sums cannot be parallelised","Vector accumulators sum in a different order, and reassociation changes the result, so the compiler may not do it silently","Floating point is too slow","Reductions require gather instructions"],1,"-ffast-math grants permission and is a real correctness change. Writing multiple accumulators explicitly is the alternative, and it breaks the dependency chain too."],
["a9","How does SIMD handle a data-dependent branch inside a loop?",["It cannot — such loops never vectorise","By masking: compute both sides for all lanes and blend, at the cost of both branches","By splitting the loop in two","By falling back to scalar for those iterations"],1,"Which means that if one side is rare and expensive, the masked version is slower than the scalar one — a real case where vectorisation loses."],
["a9","Why does array-of-structs block vectorisation?",["Structs cannot be held in vector registers","Vector loads want consecutive elements, and AoS forces slow gather instructions that may touch a different line per lane","Struct padding wastes lanes","Compilers cannot reason about structs"],1,"Struct-of-arrays removes it, which is why data layout and vectorisation are the same conversation rather than two separate optimisations."],
["a9","How should you check whether a loop vectorised?",["Time it before and after","Ask the compiler — GCC's -fopt-info-vec-missed and Clang's -Rpass-missed name the loop and the reason","Count the instructions","Inspect the profiler's IPC"],1,"Timing conflates too many effects to be diagnostic. The compiler reports it directly, and the reason almost always maps onto one of the standard blockers."],
["a9","What is a real cost of heavy 512-bit vector instructions on some processors?",["They cannot be interleaved with scalar code","They can reduce core frequency, for the whole core and for a period afterwards, eroding the gain in surrounding scalar code","They bypass the cache","They require a kernel driver"],1,"This is generation-dependent and it is a real reason to measure the whole program rather than the loop in isolation."],

// a10
["a10","What does SMT duplicate and what does it share?",["It duplicates everything except memory","It duplicates architectural state and shares execution units, caches, TLB and predictors","It duplicates caches and shares execution units","It shares only the memory controller"],1,"Which is why the gain depends entirely on how often a thread stalls: a second thread fills the units that a stalled thread leaves idle."],
["a10","When does SMT fail to help, or hurt?",["When threads are I/O bound","When threads already saturate the execution units, since each now has half the effective L1","When there are more than two threads","On single-socket machines"],1,"Dense vectorised numerical code is the classic case. Stall-heavy work — pointer chasing, branchy code — is where the 20–30% gains come from."],
["a10","Why is all-core turbo frequency lower than single-core turbo?",["Cache contention","The power and thermal budget is shared, and running every core at the single-core clock would exceed the package limit","Memory bandwidth is saturated","The interconnect adds latency"],1,"Which produces the counterintuitive result that parallelising a program reduces the clock of every core running it — a real and legitimate part of a missing speedup."],
["a10","A perfectly parallel benchmark scales to four cores and then flattens. What is the likely cause?",["A serial section appearing","Shared memory bandwidth — cores that each achieve good bandwidth alone get a fraction of it together","Cache coherence traffic","Scheduler overhead"],1,"All are possible; bandwidth saturation is the one that produces a clean flattening in genuinely independent work. Coherence traffic would make the curve turn over and decline instead."],
["a10","Why do some low-latency deployments disable SMT?",["It reduces total throughput","A sibling thread's behaviour affects tail latency through shared resources","It is incompatible with pinning","It increases power consumption"],1,"There is also a security dimension — shared predictors and caches between siblings are a side channel — which is why some mitigations involve disabling it too."],
["a10","What problem do performance and efficiency cores create?",["They cannot share memory","The scheduler must decide which core a thread belongs on, and errors show up as erratic performance","They require different compilers","They cannot run the same instruction set"],1,"Early systems did also hit an instruction-set mismatch, which is exactly the ISA-contract violation module a1 says must not happen — and it was resolved by disabling the mismatched extension."],
["a10","What is the fundamental difference between a CPU core and a GPU?",["Clock speed","A CPU minimises the latency of one thread with speculation and caches; a GPU maximises throughput by having thousands of threads ready when one stalls","Instruction set complexity","Memory bandwidth"],1,"They are opposite answers to the same question — what to do while waiting for memory — which is why dependency chains and unpredictable branches suit one and not the other."],
["a10","Why is \"add threads\" not a performance strategy on its own?",["Threads are expensive to create","Scalability is capped by serialisation, coherence traffic, shared bandwidth and the frequency drop when every core is busy","Most languages do not support threads well","The scheduler cannot handle many threads"],1,"The honest first question is whether the single-threaded version is using the machine it already has. Creation cost is real but rarely the binding constraint."],

// a11
["a11","What is the difference between Moore's law and Dennard scaling?",["They are the same observation","Moore's is about transistor density; Dennard's is about power density staying constant as transistors shrink","Moore's is about speed, Dennard's about cost","Dennard's is a corollary of Moore's"],1,"It was Dennard scaling that ended, around 2005, and that is why frequency plateaued while transistor counts kept rising."],
["a11","In P ≈ C × V² × f, which term made frequency scaling free?",["C, capacitance","V², because voltage fell with the dimensions so power fell quadratically","f, frequency","Leakage"],1,"Reducing voltage alongside the dimensions paid for both the extra transistors and the higher clock. Once voltage could not fall further, the arrangement collapsed."],
["a11","Why did voltage scaling stop?",["Manufacturing limits","Threshold voltage cannot fall proportionally without leakage current rising sharply","Higher voltage improves reliability","Power supplies could not be made more precise"],1,"By the mid-2000s leakage was a substantial fraction of total power, so lowering the threshold to permit a lower supply voltage stopped paying."],
["a11","With voltage fixed, what does a frequency increase cost?",["Linearly more power","Roughly cubically, once the voltage increase needed to switch reliably is included","Quadratically","Nothing, if the die is cooled"],1,"Which is a wall rather than a slope, and it is why clocks have sat around 3–5 GHz for two decades while transistor counts kept rising."],
["a11","What is dark silicon?",["Defective areas of a die","More transistors on a chip than can be powered simultaneously, left unpowered as a deliberate design strategy","Unused cache","Transistors that have failed over time"],1,"Fill the die with specialised units and power only what the current workload needs — which is largely what a modern phone processor is."],
["a11","If power is the binding constraint, what is the metric to optimise?",["Instructions per cycle","Operations per joule","Clock frequency","Transistor count"],1,"And specialisation is the largest single lever on it, which is why fixed-function accelerators are the current direction rather than more general cores."],
["a11","Why is benchmarking on a laptop unreliable in a specific way?",["Background processes interfere","The clock is a dependent variable — turbo and thermal limits mean a change may have measured a cooler machine","Laptops have less memory","Power saving disables cores"],1,"Pinning the frequency, disabling turbo and interleaving A and B runs are what make the comparison mean anything. Background load is a separate and more widely understood problem."],
["a11","What happened to single-thread performance after the free lunch ended?",["It stopped improving entirely","It continues to improve at a few percent a year rather than by doubling","It began to decline","It became dependent on core count"],1,"Throughput improves faster for work that can use more cores, and efficiency fastest of all for work that maps onto specialised units — which is why the skills that matter shifted to memory behaviour and parallel structure."],

// a12
["a12","What is arithmetic intensity?",["FLOPs per instruction","FLOPs divided by bytes moved from DRAM","FLOPs per second","Cache hits per FLOP"],1,"The denominator is traffic to memory rather than to cache, which is why the same code has higher intensity once its working set fits in cache."],
["a12","What does the roofline model state?",["Performance equals bandwidth times intensity","Attainable performance is the lesser of peak compute and intensity times peak bandwidth","Performance is limited by the slowest component","Speedup is bounded by the serial fraction"],1,"The whole model is that one min. Below the ridge point the second term binds; above it the first does. The last option is Amdahl's law."],
["a12","A kernel sits well below the ridge point. What will more cores buy?",["Proportional speedup","Nothing — it is memory bound, and bandwidth is already the constraint","Half the proportional speedup","It depends on the cache size"],1,"Wider vectors and cheaper arithmetic buy nothing either. What helps is moving fewer bytes: blocking, packing, struct-of-arrays."],
["a12","Why does blocking a matrix multiplication help so much?",["It reduces the number of operations","It raises arithmetic intensity by reusing each loaded block, moving the kernel along the roofline","It improves branch prediction","It enables vectorisation"],1,"The arithmetic is unchanged — O(n³) either way. Only the bytes moved change, which is exactly what intensity measures."],
["a12","Why has the ridge point moved right over the last two decades?",["Caches got larger","Compute grew far faster than memory bandwidth","Memory latency improved","Vector widths increased"],1,"Which means more kernels are memory bound than used to be, and is why so much modern optimisation is about data movement rather than arithmetic."],
["a12","A measured point sits far below both roofs. What does that indicate?",["A measurement error","Neither compute nor bandwidth is saturated — the limit is usually latency or a dependency chain","The kernel is compute bound","Insufficient parallelism in the hardware"],1,"Too few outstanding misses to cover DRAM latency is the common case. Adding cores or widening vectors will not help until that is addressed."],
["a12","What IPC would suggest a core is stalling hard?",["Above 3","Around 1","Below 0.5","IPC does not indicate stalling"],2,"On a wide core, 3–4 is good and around 1 is mediocre. Below 0.5 means most issue slots are going unused, and the top-down breakdown says why."],
["a12","Why must you measure the whole program and not just the loop you changed?",["Compilers optimise across function boundaries","A loop made four times faster that occupies 5% of runtime buys under 4%","Benchmarks are inaccurate","The loop may be inlined"],1,"The other common failures are moving time into a phase the benchmark does not cover, and trading throughput for a tail latency it does not measure. All three are visible if the whole program is timed too."],

// a13
["a13","What assumption did speculation rest on, and why was it wrong?",["That branches are predictable; they are not","That discarded work is unobservable — but a squashed load still leaves a line in the cache, and timing is measurable","That exceptions are precise; they are not","That caches are coherent; they are not"],1,"Registers are restored and memory is untouched, so nothing architectural changed. Timing is not architectural state, so the ISA contract said nothing about it."],
["a13","What are the three steps of a transient-execution attack?",["Overflow, inject, execute","Induce wrong speculation, encode a secret into microarchitectural state as an address, then recover it by timing","Read kernel memory, cache it, dump it","Poison the branch predictor, flush the cache, reload"],1,"Step two is the elegant part: the secret is never read architecturally, it is used as an index, and which cache line was fetched is what survives the squash."],
["a13","How does Spectre variant 1 work?",["It reads kernel memory directly","It trains a bounds-check branch to predict taken, then supplies an out-of-range index whose speculatively-read value selects a cache line","It corrupts the return address stack","It exploits a race in the page tables"],1,"Which is why JIT sandboxes are directly exposed — a JavaScript engine's bounds check is exactly that pattern, and the attacker controls the training."],
["a13","How did Meltdown differ from Spectre?",["It was faster","It was a specific implementation error — the permission check resolved after data was forwarded — and was fixed in hardware","It required local access","It affected only AMD processors"],1,"Spectre is speculation working as designed, which is why there is no general fix for variant 1 and gadgets are patched individually. Meltdown was a gate that should have been there."],
["a13","Why did system calls become measurably more expensive in 2018?",["New security checks were added to every call","Kernel page-table isolation stopped mapping the kernel into user page tables, so every syscall now switches page tables","Interrupt handling changed","The scheduler was rewritten"],1,"That was the Meltdown mitigation, and the cost arrived as a software update that made existing machines slower — an unusual event, and the clearest demonstration that microarchitecture is not an implementation detail."],
["a13","Why is there no general fix for Spectre variant 1?",["The hardware cannot be changed","It is a consequence of speculation working as designed rather than an implementation error","The mitigations are too slow","It requires new instruction sets"],1,"Individual gadgets are patched with a speculation barrier or an index mask, found by audit. Disabling speculation entirely would cost most of a modern core's performance."],
["a13","Why did browsers respond with site isolation rather than only patching bounds checks?",["Bounds checks cannot be patched in JavaScript","Isolation was moved to a boundary the hardware actually enforces — separate processes rather than an in-process sandbox","Site isolation is faster","It was required by standards"],1,"An in-process sandbox relies on exactly the checks speculation bypasses. Reducing timer resolution was also done, but it raises the cost of recovery without addressing the leak."],
["a13","What is the general lesson about the ISA contract?",["It should never have permitted speculation","It was incomplete rather than wrong: it specified results and said nothing about timing, and nobody needed it to until someone measured","Hardware cannot be trusted","Formal verification would have prevented it"],1,"Once an attacker can time an operation precisely, the microarchitecture is part of the interface whether it was specified or not — which is why architectures are beginning to specify what must not be observable."]

];
